---
- name: Our first play
  hosts: planetexpress:farnsworth

  tasks:
    - name: Install steam locomotive on All machines
      apt:
        name: sl
        state: present
      become: yes     ## run as sudo
